# Generated by Django 5.1.4 on 2024-12-21 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_postlike_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentlike',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_like', to='my_app.comment'),
        ),
    ]
